package resposta;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import utils.reprodutorMidia;

import java.awt.event.KeyEvent;

/**
 *
 * @author cesar
 */
public class RespostaCerta extends javax.swing.JFrame {

    boolean ultima = false;
    String[] conta;

    // private jogo.Jogo JogoAtual;
    /**
     * Creates new form respostaCerta
     */
    public RespostaCerta() {
        initComponents();
    }

    public RespostaCerta(boolean ultima, String[] conta) {
        this.ultima = ultima;
        this.conta = conta;
        initComponents();
        if (ultima == true) {
            descricaoCerto.setText("Você finalizou o jogo!");
        } else {
            reprodutorMidia som = new reprodutorMidia("src/resources/certa.wav");
            som.tocar();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconeCerto = new javax.swing.JLabel();
        tituloCerto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        descricaoCerto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setLayout(null);

        iconeCerto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/certoIcone.png"))); // NOI18N
        jPanel1.add(iconeCerto);
        iconeCerto.setBounds(130, 10, 140, 140);

        tituloCerto.setFont(new java.awt.Font("Krungthep", 1, 24)); // NOI18N
        tituloCerto.setForeground(new java.awt.Color(79, 186, 111));
        tituloCerto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloCerto.setText("Resposta Certa!");
        jPanel1.add(tituloCerto);
        tituloCerto.setBounds(0, 160, 400, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("(Enter)");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 240, 70, 40);

        descricaoCerto.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        descricaoCerto.setForeground(new java.awt.Color(79, 186, 111));
        descricaoCerto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descricaoCerto.setText("Você acertou essa pergunta!");
        jPanel1.add(descricaoCerto);
        descricaoCerto.setBounds(0, 190, 400, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/botaoOK.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                jLabel1KeyPressed(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 240, 213, 40);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        setBounds(450, 350, 400, 322);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1KeyPressed(KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyPressed

    }//GEN-LAST:event_jLabel1KeyPressed

    private void formKeyPressed(KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.dispose();
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RespostaCerta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RespostaCerta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RespostaCerta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RespostaCerta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RespostaCerta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descricaoCerto;
    private javax.swing.JLabel iconeCerto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tituloCerto;
    // End of variables declaration//GEN-END:variables

}
