package utils;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import login.Login;
import menu.MenuPrincipal;

import javax.swing.*;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author cesar
 */
public class telaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form menu.MenuPrincipal
     */
    public telaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel titleLeft = new javax.swing.JLabel();
        javax.swing.JLabel tituloLogin = new javax.swing.JLabel();
        javax.swing.JLabel tituloEmail = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        javax.swing.JLabel tituloSenha = new javax.swing.JLabel();
        inputSenha = new javax.swing.JPasswordField();
        javax.swing.JLabel tituloNome = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        javax.swing.JLabel tituloCargo = new javax.swing.JLabel();
        inputCargo = new javax.swing.JTextField();
        javax.swing.JLabel btnCadastrarConta = new javax.swing.JLabel();
        javax.swing.JLabel fundoLogin = new javax.swing.JLabel();
        javax.swing.JLabel madeText = new javax.swing.JLabel();
        javax.swing.JLabel btnSair = new javax.swing.JLabel();
        javax.swing.JLabel background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setLayout(null);

        titleLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/title_left.png"))); // NOI18N
        jPanel1.add(titleLeft);
        titleLeft.setBounds(20, 20, 216, 34);

        tituloLogin.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        tituloLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLogin.setText("Cadastro");
        jPanel1.add(tituloLogin);
        tituloLogin.setBounds(270, 150, 780, 50);

        tituloEmail.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        tituloEmail.setText("E-MAIL:");
        jPanel1.add(tituloEmail);
        tituloEmail.setBounds(370, 270, 110, 24);

        inputEmail.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jPanel1.add(inputEmail);
        inputEmail.setBounds(490, 260, 480, 40);

        tituloSenha.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        tituloSenha.setText("SENHA:");
        jPanel1.add(tituloSenha);
        tituloSenha.setBounds(370, 330, 110, 24);
        jPanel1.add(inputSenha);
        inputSenha.setBounds(490, 320, 480, 40);

        tituloNome.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        tituloNome.setText("NOME:");
        jPanel1.add(tituloNome);
        tituloNome.setBounds(370, 390, 110, 24);

        inputNome.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jPanel1.add(inputNome);
        inputNome.setBounds(490, 380, 480, 40);

        tituloCargo.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        tituloCargo.setText("CARGO:");
        jPanel1.add(tituloCargo);
        tituloCargo.setBounds(370, 450, 110, 24);

        inputCargo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        inputCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                inputCargoKeyPressed(evt);
            }
        });
        jPanel1.add(inputCargo);
        inputCargo.setBounds(490, 440, 480, 40);

        btnCadastrarConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/botaoCriarCadastro.png"))); // NOI18N
        btnCadastrarConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarContaMouseClicked(evt);
            }
        });
        jPanel1.add(btnCadastrarConta);
        btnCadastrarConta.setBounds(550, 530, 290, 50);

        fundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/backgroundConquistas.png"))); // NOI18N
        jPanel1.add(fundoLogin);
        fundoLogin.setBounds(270, 130, 784, 500);

        madeText.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        madeText.setForeground(new java.awt.Color(255, 255, 255));
        madeText.setText("FEITO POR CESAR VERGARA");
        jPanel1.add(madeText);
        madeText.setBounds(20, 730, 260, 30);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/botaoVoltar.png"))); // NOI18N
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        jPanel1.add(btnSair);
        btnSair.setBounds(1140, 710, 210, 45);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/fundo_sistema.jpg"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 1366, 770);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        Login entrar = new Login();
        entrar.setLocationRelativeTo(null);
        entrar.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnSairMouseClicked

    private boolean validarDados() {
        if (inputEmail.getText().length() < 7) {
            JOptionPane.showMessageDialog(null, "E-mail invalido.");
            return false;
        } else if (inputSenha.getPassword().length < 5) {
            JOptionPane.showMessageDialog(null, "A senha precisa ter no mínimo 5 caracteres.");
            return false;
        } else if (inputNome.getText().length() < 5) {
            JOptionPane.showMessageDialog(null, "O nome precisa ter no mínimo 5 caracteres.");
            return false;
        } else if (inputCargo.getText().length() < 5) {
            JOptionPane.showMessageDialog(null, "O cargo precisa ter no mínimo 5 caracteres.");
            return false;
        }
        return true;
    }

    private void limparForm() {
        inputEmail.setText("");
        inputSenha.setText("");
        inputNome.setText("");
        inputCargo.setText("");
    }

    private void criarConta() {
        if (validarDados()) {
            File f = new File(inputEmail.getText() + ".txt");
            //File f = new File("jogadores" + ".txt");
            if (f.exists()) {
                JOptionPane.showMessageDialog(null, "Esse e-mail já possui uma conta vinculada.");
            } else {
                //try (PrintWrite out = new PrintWrite(inputEmail.getText() + ".txt"){
                try (PrintWriter out = new PrintWriter(inputEmail.getText() + ".txt")) {
                    String strPass = new String(inputSenha.getPassword()).trim();
                    int[] conquistas = new int[6];
                    for (int i = 0; i < 6; i++) {
                        conquistas[i] = 0;
                    }
                    out.println(inputEmail.getText() + "," + strPass + "," + inputNome.getText() + "," + inputCargo.getText() + ",0,0," + conquistas[0] + "," + conquistas[1] + "," + conquistas[2] + "," + conquistas[3] + "," + conquistas[4] + "," + conquistas[5]);
                    JOptionPane.showMessageDialog(null, "Conta criada com sucesso.");
                    limparForm();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(telaCadastro.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    private void btnCadastrarContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarContaMouseClicked
        criarConta();
    }//GEN-LAST:event_btnCadastrarContaMouseClicked

    private void inputCargoKeyPressed(KeyEvent evt) {//GEN-FIRST:event_inputCargoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            criarConta();
    }//GEN-LAST:event_inputCargoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new telaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextField inputCargo;
    javax.swing.JTextField inputEmail;
    javax.swing.JTextField inputNome;
    javax.swing.JPasswordField inputSenha;
    // End of variables declaration//GEN-END:variables

}
