package home;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//import java.awt.event.KeyEvent;

import game.Game;
import game.GameInstruction;
import game.JogoInstrucaoNota;
import login.Login;

import javax.swing.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author cesar
 */
public class Home extends javax.swing.JFrame {

    String[] conta = null;

    /**
     * Creates new form NewJFrame
     */
    public Home() {
        initComponents();
    }

    public Home(String[] conta) {
        initComponents();
        this.conta = conta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jogoCFOP = new javax.swing.JLabel();
        btnJogar = new javax.swing.JLabel();
        btnConquistas = new javax.swing.JLabel();
        javax.swing.JLabel btnSair = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setLayout(null);

        jogoCFOP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/titulo.png"))); // NOI18N
        jPanel1.add(jogoCFOP);
        jogoCFOP.setBounds(320, 80, 730, 130);

        btnJogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/botaoJogar.png"))); // NOI18N
        btnJogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJogarMouseClicked(evt);
            }
        });
        jPanel1.add(btnJogar);
        btnJogar.setBounds(510, 260, 354, 90);

        btnConquistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/botaoConquistas.png"))); // NOI18N
        btnConquistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConquistasMouseClicked(evt);
            }
        });
        jPanel1.add(btnConquistas);
        btnConquistas.setBounds(510, 380, 354, 89);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/botaoSair.png"))); // NOI18N
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        jPanel1.add(btnSair);
        btnSair.setBounds(510, 500, 354, 89);

        jLabel1.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FEITO POR CESAR VERGARA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 730, 260, 30);

        background.setBackground(new java.awt.Color(255, 255, 204));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/fundo_sistema.jpg"))); // NOI18N
        background.setToolTipText("");
        jPanel1.add(background);
        background.setBounds(0, 0, 1366, 770);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        int result = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja encerrar o login?", "Encerrar Login",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            Login entrar = new Login();
            entrar.setLocationRelativeTo(null);
            entrar.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSairMouseClicked

    //metodo chamar classe JogoIntrucao
    public void chamarInstrucao() {
        GameInstruction jogoIns = new GameInstruction(conta);
        jogoIns.setLocationRelativeTo(null);
        jogoIns.setVisible(true);
        this.dispose();
    }

    //metodo chamar classe jogo.JogoInstrucaoNota
    public void chamarInstrucaoNota() {
        JogoInstrucaoNota jogoInsNota = new JogoInstrucaoNota(conta);
        jogoInsNota.setLocationRelativeTo(null);
        jogoInsNota.setVisible(true);
        this.dispose();
    }

    //ler aquivo ranking e verificar se jogador já completou fases
    public void validarJogadorFase() {
        int escolheFase = 0;
        int i = 0;
        Game jogo = Game.getInstance();

        try {
            FileReader arqFase = new FileReader("rankingFase1.txt");
            BufferedReader linhaFase = new BufferedReader(arqFase);
            String val;

            while ((val = linhaFase.readLine()) != null && escolheFase == 0) {
                String fase = val.split(",")[0];
                String login = val.split(",")[1];
                if (Integer.parseInt(fase) == 1 && jogo.getLogin().equals(login)) {
                    escolheFase = 3;
                    String[] opcao = {"Voltar Fase 1", " Seguir Fase 2"};
                    int result = JOptionPane.showOptionDialog(null, "jogador.Jogador já completou alguma fase. O que deseja fazer?", "Fases do jogo.Jogo!",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE,
                            null, opcao, opcao[0]);
                    if (result == JOptionPane.YES_OPTION) {
                        escolheFase = 1;
                    }
                    if (result == JOptionPane.NO_OPTION) {
                        escolheFase = 2;
                    }
                }
                i++;
            }
        } catch (IOException ex) {
            System.out.println("JOGADOR NÃO EXISTE");
            //  chamarInstrucao();
        }
        if (escolheFase == 1 || escolheFase == 0) {
            chamarInstrucao();
        }
        if (escolheFase == 2) {
            chamarInstrucaoNota();
        }
    }
    private void btnJogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJogarMouseClicked
        validarJogadorFase();
    }//GEN-LAST:event_btnJogarMouseClicked

    private void btnConquistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConquistasMouseClicked
        Achievements verConquistas = new Achievements(conta);
        verConquistas.setLocationRelativeTo(null);
        verConquistas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConquistasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel btnConquistas;
    javax.swing.JLabel btnJogar;
    // End of variables declaration//GEN-END:variables

}
