package menu;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
//import javax.swing.JOptionPane;

/**
 * @author cesar
 */
public class Conquistas extends javax.swing.JFrame {

    private static final int TROFEU1 = 6;
    private static final int TROFEU2 = 7;
    private static final int TROFEU3 = 8;
    private static final int TROFEU4 = 9;
    private static final int TROFEU5 = 10;
    private static final int TROFEU6 = 11;
    String[] conta = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel star1;
    javax.swing.JLabel star2;
    javax.swing.JLabel star3;
    javax.swing.JLabel star4;
    javax.swing.JLabel star5;
    javax.swing.JLabel star6;

    /**
     * Creates new form menu.MenuPrincipal
     */
    public Conquistas() {
        initComponents();
    }
    /**
     * Creates new form menu.MenuPrincipal
     */
    public Conquistas(String[] conta) {
        initComponents();
        this.conta = conta;
        preencherConquistas();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conquistas().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel titleLeft = new javax.swing.JLabel();
        javax.swing.JLabel iconConquistas = new javax.swing.JLabel();
        javax.swing.JLabel tituloConquistas = new javax.swing.JLabel();
        star1 = new javax.swing.JLabel();
        javax.swing.JLabel tituloStar1 = new javax.swing.JLabel();
        javax.swing.JLabel descricaoStar1 = new javax.swing.JLabel();
        star2 = new javax.swing.JLabel();
        javax.swing.JLabel tituloStar2 = new javax.swing.JLabel();
        javax.swing.JLabel descricaoStar2 = new javax.swing.JLabel();
        star3 = new javax.swing.JLabel();
        javax.swing.JLabel tituloStar3 = new javax.swing.JLabel();
        javax.swing.JLabel descricaoStar3 = new javax.swing.JLabel();
        star4 = new javax.swing.JLabel();
        javax.swing.JLabel tituloStar4 = new javax.swing.JLabel();
        javax.swing.JLabel descricaoStar4 = new javax.swing.JLabel();
        star5 = new javax.swing.JLabel();
        javax.swing.JLabel tituloStar5 = new javax.swing.JLabel();
        javax.swing.JLabel descricaoStar5 = new javax.swing.JLabel();
        star6 = new javax.swing.JLabel();
        javax.swing.JLabel tituloStar6 = new javax.swing.JLabel();
        javax.swing.JLabel descricaoStar6 = new javax.swing.JLabel();
        javax.swing.JLabel btnVoltar = new javax.swing.JLabel();
        javax.swing.JLabel backgroundConquistas = new javax.swing.JLabel();
        javax.swing.JLabel madeText = new javax.swing.JLabel();
        javax.swing.JLabel background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setLayout(null);

        titleLeft.setIcon(new ImageIcon(getClass().getResource("/resources/title_left.png"))); // NOI18N
        jPanel1.add(titleLeft);
        titleLeft.setBounds(20, 20, 216, 34);

        iconConquistas.setIcon(new ImageIcon(getClass().getResource("/resources/conquistasIcone.png"))); // NOI18N
        jPanel1.add(iconConquistas);
        iconConquistas.setBounds(680, 100, 80, 78);

        tituloConquistas.setFont(new java.awt.Font("Krungthep", 1, 36)); // NOI18N
        tituloConquistas.setForeground(new java.awt.Color(221, 87, 144));
        tituloConquistas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloConquistas.setText("CONQUISTAS");
        tituloConquistas.setToolTipText("");
        jPanel1.add(tituloConquistas);
        tituloConquistas.setBounds(320, 190, 780, 50);

        star1.setIcon(new ImageIcon(getClass().getResource("/resources/starGray.png"))); // NOI18N
        jPanel1.add(star1);
        star1.setBounds(400, 290, 46, 44);

        tituloStar1.setFont(new java.awt.Font("Krungthep", 1, 24)); // NOI18N
        tituloStar1.setForeground(new java.awt.Color(255, 193, 7));
        tituloStar1.setText("APRENDIZ");
        jPanel1.add(tituloStar1);
        tituloStar1.setBounds(460, 280, 200, 40);

        descricaoStar1.setFont(new java.awt.Font("Krungthep", 0, 14)); // NOI18N
        descricaoStar1.setForeground(new java.awt.Color(255, 193, 7));
        descricaoStar1.setText("Iniciou o jogo uma vez");
        jPanel1.add(descricaoStar1);
        descricaoStar1.setBounds(460, 310, 200, 40);

        star2.setIcon(new ImageIcon(getClass().getResource("/resources/starGray.png"))); // NOI18N
        jPanel1.add(star2);
        star2.setBounds(770, 290, 46, 44);

        tituloStar2.setFont(new java.awt.Font("Krungthep", 1, 24)); // NOI18N
        tituloStar2.setForeground(new java.awt.Color(255, 193, 7));
        tituloStar2.setText("LIGEIRINHO");
        jPanel1.add(tituloStar2);
        tituloStar2.setBounds(830, 280, 220, 40);

        descricaoStar2.setFont(new java.awt.Font("Krungthep", 0, 14)); // NOI18N
        descricaoStar2.setForeground(new java.awt.Color(255, 193, 7));
        descricaoStar2.setText("Acertou uma pergunta rápido");
        jPanel1.add(descricaoStar2);
        descricaoStar2.setBounds(830, 310, 250, 40);

        star3.setIcon(new ImageIcon(getClass().getResource("/resources/starGray.png"))); // NOI18N
        jPanel1.add(star3);
        star3.setBounds(400, 390, 46, 44);

        tituloStar3.setFont(new java.awt.Font("Krungthep", 1, 24)); // NOI18N
        tituloStar3.setForeground(new java.awt.Color(255, 193, 7));
        tituloStar3.setText("VELOZ");
        jPanel1.add(tituloStar3);
        tituloStar3.setBounds(460, 380, 200, 40);

        descricaoStar3.setFont(new java.awt.Font("Krungthep", 0, 14)); // NOI18N
        descricaoStar3.setForeground(new java.awt.Color(255, 193, 7));
        descricaoStar3.setText("Acertou 5 perguntas seguidas");
        jPanel1.add(descricaoStar3);
        descricaoStar3.setBounds(460, 410, 230, 40);

        star4.setIcon(new ImageIcon(getClass().getResource("/resources/starGray.png"))); // NOI18N
        jPanel1.add(star4);
        star4.setBounds(770, 390, 46, 44);

        tituloStar4.setFont(new java.awt.Font("Krungthep", 1, 24)); // NOI18N
        tituloStar4.setForeground(new java.awt.Color(255, 193, 7));
        tituloStar4.setText("CRAQUE");
        jPanel1.add(tituloStar4);
        tituloStar4.setBounds(830, 380, 170, 40);

        descricaoStar4.setFont(new java.awt.Font("Krungthep", 0, 14)); // NOI18N
        descricaoStar4.setForeground(new java.awt.Color(255, 193, 7));
        descricaoStar4.setText("Acertou 08 perguntas seguidas");
        jPanel1.add(descricaoStar4);
        descricaoStar4.setBounds(830, 410, 250, 40);

        star5.setIcon(new ImageIcon(getClass().getResource("/resources/starGray.png"))); // NOI18N
        jPanel1.add(star5);
        star5.setBounds(400, 490, 46, 44);

        tituloStar5.setFont(new java.awt.Font("Krungthep", 1, 24)); // NOI18N
        tituloStar5.setForeground(new java.awt.Color(255, 193, 7));
        tituloStar5.setText("INVENCÍVEL");
        jPanel1.add(tituloStar5);
        tituloStar5.setBounds(460, 480, 220, 40);

        descricaoStar5.setFont(new java.awt.Font("Krungthep", 0, 14)); // NOI18N
        descricaoStar5.setForeground(new java.awt.Color(255, 193, 7));
        descricaoStar5.setText("Completou um nível sem errar");
        jPanel1.add(descricaoStar5);
        descricaoStar5.setBounds(460, 510, 240, 40);

        star6.setIcon(new ImageIcon(getClass().getResource("/resources/starGray.png"))); // NOI18N
        jPanel1.add(star6);
        star6.setBounds(770, 490, 46, 44);

        tituloStar6.setFont(new java.awt.Font("Krungthep", 1, 24)); // NOI18N
        tituloStar6.setForeground(new java.awt.Color(255, 193, 7));
        tituloStar6.setText("FISCAL");
        jPanel1.add(tituloStar6);
        tituloStar6.setBounds(830, 480, 150, 40);

        descricaoStar6.setFont(new java.awt.Font("Krungthep", 0, 14)); // NOI18N
        descricaoStar6.setForeground(new java.awt.Color(255, 193, 7));
        descricaoStar6.setText("Completou o game");
        jPanel1.add(descricaoStar6);
        descricaoStar6.setBounds(830, 510, 250, 40);

        btnVoltar.setIcon(new ImageIcon(getClass().getResource("/resources/botaoVoltar.png"))); // NOI18N
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
        });
        jPanel1.add(btnVoltar);
        btnVoltar.setBounds(620, 630, 210, 45);

        backgroundConquistas.setIcon(new ImageIcon(getClass().getResource("/resources/backgroundConquistas.png"))); // NOI18N
        jPanel1.add(backgroundConquistas);
        backgroundConquistas.setBounds(320, 60, 784, 650);

        madeText.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        madeText.setForeground(new java.awt.Color(255, 255, 255));
        madeText.setText("FEITO POR CESAR VERGARA");
        jPanel1.add(madeText);
        madeText.setBounds(20, 730, 260, 30);

        background.setIcon(new ImageIcon(getClass().getResource("/resources/fundo_sistema.jpg"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 1366, 770);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        MenuPrincipal jogo = new MenuPrincipal(conta);
        jogo.setLocationRelativeTo(null);
        jogo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarMouseClicked

    private void preencherConquistas() {
        ImageIcon estrela = new ImageIcon(getClass().getResource("/resources/starIcon.png"));
        if (conta[TROFEU1].equals("1")) {
            star1.setIcon(estrela);
        }
        if (conta[TROFEU2].equals("1")) {
            star2.setIcon(estrela);
        }
        if (conta[TROFEU3].equals("1")) {
            star3.setIcon(estrela);
        }
        if (conta[TROFEU4].equals("1")) {
            star4.setIcon(estrela);
        }
        if (conta[TROFEU5].equals("1")) {
            star5.setIcon(estrela);
        }
        if (conta[TROFEU6].equals("1")) {
            star6.setIcon(estrela);
        }
    }
    // End of variables declaration//GEN-END:variables

}
